-- MySQL Script generated by MySQL Workbench
-- Thu Oct 19 18:56:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Bolo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bolo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bolo` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `valorUnitario` DOUBLE NOT NULL,
  `peso` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `RG` VARCHAR(20) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `CEP` VARCHAR(20) NOT NULL,
  `celular` VARCHAR(13) NOT NULL,
  `telefoneResidencial` VARCHAR(13) NOT NULL,
  `telefoneComercial` VARCHAR(13) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doce`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Doce` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Doce` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `valorUnitario` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DoceSelecionado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DoceSelecionado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DoceSelecionado` (
  `quantidade` INT NOT NULL,
  `fk_idDoce` INT NOT NULL,
  `fk_idOrcamentoBuffetCompleto` INT NOT NULL,
  PRIMARY KEY (`fk_idOrcamentoBuffetCompleto`, `fk_idDoce`),
  INDEX `fk_idOrcamentoBuffetCompleto_idx` (`fk_idOrcamentoBuffetCompleto` ASC) VISIBLE,
  INDEX `fk_idDoce_idx` (`fk_idDoce` ASC) VISIBLE,
  CONSTRAINT `fk_idOrcamentoBuffetCompleto`
    FOREIGN KEY (`fk_idOrcamentoBuffetCompleto`)
    REFERENCES `mydb`.`OrcamentoBuffetCompleto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idDoce`
    FOREIGN KEY (`fk_idDoce`)
    REFERENCES `mydb`.`Doce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrcamentoBuffetCompleto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`OrcamentoBuffetCompleto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`OrcamentoBuffetCompleto` (
  `id` INT NOT NULL,
  `numeroDeConvidados` INT NOT NULL,
  `numeroDeColaboradores` INT NOT NULL,
  `horaDeInicio` VARCHAR(8) NOT NULL,
  `data` VARCHAR(10) NOT NULL,
  `teraCerveja` TINYINT NOT NULL,
  `fk_cpfCliente` VARCHAR(11) NOT NULL,
  `fk_idBolo` INT NOT NULL,
  `fk_idPagamento` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cpfCliente_idx` (`fk_cpfCliente` ASC) VISIBLE,
  CONSTRAINT `fk_cpfCliente`
    FOREIGN KEY (`fk_cpfCliente`)
    REFERENCES `mydb`.`Cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idBolo`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`Bolo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idPagamento`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`Pagamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrcamentoLocacaoDeEspaco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`OrcamentoLocacaoDeEspaco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`OrcamentoLocacaoDeEspaco` (
  `id` INT NOT NULL,
  `numeroDeConvidados` INT NOT NULL,
  `numeroDeColaboradores` INT NOT NULL,
  `horaDeInicio` VARCHAR(8) NOT NULL,
  `data` VARCHAR(10) NOT NULL,
  `fk_cpfCliente` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cpfCliente_idx` (`fk_cpfCliente` ASC) VISIBLE,
  CONSTRAINT `fk_cpfCliente`
    FOREIGN KEY (`fk_cpfCliente`)
    REFERENCES `mydb`.`Cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pagamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `id` INT NOT NULL,
  `valorTotal` DOUBLE NOT NULL,
  `formaDePagamento` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Salgado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Salgado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Salgado` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `valorUnitario` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SalgadoSelecionado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SalgadoSelecionado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SalgadoSelecionado` (
  `quantidade` INT NOT NULL,
  `fk_idSalgado` INT NOT NULL,
  `fk_idOrcamentoBuffetCompleto` INT NOT NULL,
  INDEX `fk_idSalgado_idx` (`fk_idSalgado` ASC) VISIBLE,
  INDEX `fk_idOrcamentoBuffetCompleto_idx` (`fk_idOrcamentoBuffetCompleto` ASC) VISIBLE,
  PRIMARY KEY (`fk_idOrcamentoBuffetCompleto`, `fk_idSalgado`),
  CONSTRAINT `fk_idSalgado`
    FOREIGN KEY (`fk_idSalgado`)
    REFERENCES `mydb`.`Salgado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idOrcamentoBuffetCompleto`
    FOREIGN KEY (`fk_idOrcamentoBuffetCompleto`)
    REFERENCES `mydb`.`OrcamentoBuffetCompleto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ServicoAdicional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ServicoAdicional` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ServicoAdicional` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ServicoContratado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ServicoContratado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ServicoContratado` (
  `fk_idServicoAdicional` INT NOT NULL,
  `fk_idOrcamentoLocacaoDeEspaco` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`fk_idServicoAdicional`, `fk_idOrcamentoLocacaoDeEspaco`),
  INDEX `fk_idOrcamentoLocacaoDeEspaco_idx` (`fk_idOrcamentoLocacaoDeEspaco` ASC) VISIBLE,
  CONSTRAINT `fk_idOrcamentoLocacaoDeEspaco`
    FOREIGN KEY (`fk_idOrcamentoLocacaoDeEspaco`)
    REFERENCES `mydb`.`OrcamentoLocacaoDeEspaco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idServicoAdicional`
    FOREIGN KEY (`fk_idServicoAdicional`)
    REFERENCES `mydb`.`ServicoAdicional` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `login` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(500) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `tipoDeUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`parcela`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`parcela` ;

CREATE TABLE IF NOT EXISTS `mydb`.`parcela` (
  `id` INT NOT NULL,
  `valorPago` DOUBLE NOT NULL,
  `dataVencimento` VARCHAR(10) NOT NULL,
  `dataPagamento` VARCHAR(10) NOT NULL,
  `fk_idPagamento` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_idPagamento`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`Pagamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
